---
- name: Playbool
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: "Install pip dependencies"
      pip:
        name:
          - simplegmail>=4.0.2
        executable: pip3